### ISSUE TITLE
links with other initiatives - future handling of meta data ?

### ISSUE THREAD

**Issue by jbpoline** [Brainhack-Proceedings-2015/Cipollini_HBM_NiData#2]
Hi Ben, Ariel, 

This would be a very useful package ... While reading the brainhack proceedings, I thought that there was a comprehensive section 2 (I assumed a one page constraint) but less on other related initiatives (datalad ? others?).   The example with dipy is great.  The other big thing is how we go about standardizing the description of the meta data, would be great to see some links with NIDM at some stage (not to be discuss in this paper, just thoughts for the future).

**Comment by bcipolli** [comment]
I added a sentence to the end of section 2 mentioning datalad and NIDM, just to mention the relationship :) Will send a PR shortly and close this out.
